### ISSUE TITLE
Razer Ornata V3 X doesn't work in gtk-razer.

### ISSUE THREAD

**Issue by VikOlliver** [rsmith-nl/scripts#5] opened 2023-03-07 21:01 UTC
vik@xyz:~/bin$ ./gtk-razer.pyw 
  File "./gtk-razer.pyw", line 5
SyntaxError: Non-ASCII character '\xc2' in file ./gtk-razer.pyw on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by VikOlliver** [comment] 2023-03-07 21:23
OK, to get this to run at all I needed to change the first line to:
#!/usr/bin/env python3

And install:
sudo apt-get install python3-usb

Then I get:

Traceback (most recent call last):
  File "./gtk-razer.pyw", line 214, in <module>
    state = create_state()
  File "./gtk-razer.pyw", line 156, in create_state
    state.model = devs[0].product
  File "/usr/lib/python3/dist-packages/usb/core.py", line 841, in product
    self._product = util.get_string(self, self.iProduct)
  File "/usr/lib/python3/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid

Should've mentioned it's an Ornata v3 X keyboard.

**Comment by VikOlliver** [comment] 2023-03-07 21:48
I need to run the script as root to avoid the langid error:
sudo ./gtk-razer.pyw

This brings up the GUI (Hoorayy!!). Then when I try to set a colour I get:

Traceback (most recent call last):
  File "./gtk-razer.pyw", line 143, in set_color
    state.dev.ctrl_transfer(0x21, 0x09, 0x300, 0x01, msg)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy


Should've mentioned it's an Ornata v3 X keyboard.

**Comment by rsmith-nl** [comment] 2023-03-09 06:30
Based on the `openrazer` Linux driver, it appears that for an Ornata keyboard (instead of an Ornata Chroma) in `set_color` you should change the penultimate parameter (the "report index") of `state.dev.ctrl_transfer` from 0x01 to 0x02. 
That is *assuming* that the Ornata v3 behaves the same as the Ornata v2.

If you want to be able to set the color without using `sudo`, you could add your user-id to a group (e.g. `usb`) and give that group write permissions on USB devices.

**Comment by VikOlliver** [comment] 2023-03-10 22:37
I tried making the change, and it didn't seem to change the behaviour. I guess the v3 is a different beast. For what it's worth I changed it to 0x03 just for giggles and got:

  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

Which may not be useful, but does show I'm editing the right file :)

**Comment by rsmith-nl** [comment] 2023-03-11 10:29
If you look at the [`openrazer`](https://github.com/openrazer/openrazer) driver code that I used as a reference for writing this, you will see that there are significant differences between keyboards. There is no mention of the Ornata V3 X in the openrazer code. It could be that the V3 X simply uses some other constants (like the `transaction_id`) than the V2.

OTOH, looking at the reviews, it only has a single lighting zone instead of individually programmable keys, so it might be a completely different beast.

If you don't want to wait for openrazer to support your device so you can check what is different, you'll have to e.g. install the official razer synapse driver in a ms-windows VM and snoop the USB traffic while changing the static color.

**Comment by rsmith-nl** [comment] 2023-03-11 21:52
Looking at [this](https://github.com/lukester1975/openrazer/blob/ornata-v3-hackery/driver/razerkbd_driver.c), it seems that the Ornata V3 uses a `transaction_id` of `0x1F`.

In `static_color_msg`, try changing `hdr = b'\x00\x3f\x00\x00\x00\x09\x0f\x02'` to `hdr = b'\x00\x1f\x00\x00\x00\x09\x0f\x02'` (undo any changes made to `set_color` first).

**Comment by VikOlliver** [comment] 2023-03-12 22:55
Thanks for the suggestion though not much luck (with or without set_color changes). I note [here](https://github.com/openrazer/openrazer/pull/1940#issuecomment-1448655076)  that @lukester1975 reports "wacky static behaviour" and implements a workaround by setting a polychromatic pattern with all elements set to the same colour. If I interpret the thread right, things flick on and off when keys are pressed. Weirdness is afoot...

**Comment by rsmith-nl** [comment] 2023-03-13 22:56
Based on that capture, the following `static_color_msg` function for the Ornata V3 should work.

```
import array

def static_color_msg(red, green, blue):
    """
    Create a message to set the Razer Ornata V3 lights to a static color.
    All arguments should be an number in the range 0-255.

    Returns an array object containing the message ready to feed into a ctrl_transfer.
    """
    msg = array.array("B", b'\x00'*90)
    msg[1] = 0x1F  # transaction id
    msg[5] = 0x23  # data_size
    msg[6] = 0x0F  # command class
    msg[7] = 0x03  # command id
    msg[12] = 0x09  # unknown
    r, g, b = int(red), int(green), int(blue)
    for j in range(13, 41, 3):
        msg[j], msg[j+1], msg[j+2] = r, g, b
    chksum = 0
    for j in msg[2:-2]:
        chksum ^= j
    msg[88] = chksum
    return msg
```

**Comment by VikOlliver** [comment] 2023-03-13 23:11
Sadly, no go. Here's the result. BTW I re-downloaded the script to make sure it was clean and I'm running as root so as to dodge any permission issues.

vik@Condor:~/bin$ Traceback (most recent call last):
  File "./gtk-razer.pyw", line 165, in set_color
    state.dev.ctrl_transfer(0x21, 0x09, 0x300, 0x01, msg)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 1034, in ctrl_transfer
    self._ctx.managed_claim_interface(self, interface_number)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

**Comment by rsmith-nl** [comment] 2023-03-14 22:10
Well, then I'm out of ideas. At this point my suggestion would be to wait until the issue is fixed in the openrazer code. Then you can fork `gtk-razer` and port the fix.

It's has never been my intention to have `gtk-razer` support every Razer keyboard out there. Just the ones that I have access to. So I will close this issue now.

**Closed as not planned by rsmith-nl** 2023-03-14 22:10 UTC

**Comment by VikOlliver** [comment] 2023-03-15 19:04
I appreciate the effort you have put in. If I get any further I'll submit my findings.
